#!/bin/bash
#Color SYStem 
 
DARK=`echo -en "\e[100m"`
bold=`echo -en "\e[1m"`
normal=`echo -en "\e[0m"`
red=`echo -en "\e[31m"`

# Tool is STartINg 

clear 

figlet "prabhxhacker" | lolcat -f |  boxes -d unicornthink 

sleep 2


# Ip SEttIng 

echo "$bold$red**************SCANING IP*****************$normal"  
sleep 2 

main=$(ifconfig | grep "broadcast" | cut -d " " -f 10 | cut -d "." -f 1,2,3)

echo "$Red$bold{Scanning Only For Working Ip's Under 1 to 245} $normal "

file="log.txt"

if [ -f "$file" ] ; then
    rm "$file"
fi


for ips in {1..245}
do 
       ping -c 1 $main.$ips | grep "64 bytes" | cut -d " " -f 4 | tr -d ":" >> log.txt &  

 
done 

loop=$(cat log.txt)

clear
 
echo "$red$bold YOU_CAN_INPUT_ANY_IP $normal "
 

sleep 4 

clear 

sleep 2



echo "$red$bold ************** NOW Scaning Top Ports ***************$normal "
sudo nmap -sS --top-ports 20  -iL log.txt 
 
sleep 2 

echo "$red $bold | This IS Your IP's | $normal "
boxes log.txt 

sleep 1
o=y 
while [ "$o" = "y" ] 
do 
echo "$red$bold | Do FIRST PING THIS IP'S | $normal "
sleep 1 
read -p "IP : " i 

ping -c 1 -W 1 "$i"
t=$(echo "$?")
if [ "$t" = "0" ]
then 
  echo "$red $bold Your Ip is Running $normal  "
else 
  echo "Try Another Ip!!!"
fi
read -p "$DARK $bold Do U want Ping Again [y/n]: $normal " o 

done 
sleep 2 

echo "$red $bold YOu can Select Ip From list\nYou can give any ip  $normal"

sleep 2

echo "$DARK $bold Type Full IP $normal "


sleep 5 


read -p "$DARK $bold Select IP  : $normal " target 

sleep 2 

echo "$red$bold********************* Select Port From Top Port ***********************$normal"
sleep 1 
read -p "$DARk$bold |Input ANY PORT /  Or select given port :$normal" port 

t=y
while [ "$t" = "y" ]
do 

boxes main.txt 
sleep 2

read -p "$DARk$bold Select number :$normal" answer 

# if flag start 
#1

if [ $answer = 1 ]
then 
  sudo nmap -sT $port $target 

fi 

#2

if [ $answer = 2 ]
then 
  sudo nmap -Pn --script vuln $port $target 

fi 
#3

if [ $answer = 3 ]
then 
  sudo nmap -S  $port $target 

fi 

#4 

if [ $answer = 4 ]
then 
  sudo nmap -PA $port $target 

fi 

#5 

if [ $answer = 5 ]
then 
  sudo nmap -PS $port $target 

fi 

#6

if [ $answer = 6 ]
then 
  sudo nmap -PU $port $target 

fi 

#7 

if [ $answer = 7 ]
then 
  sudo nmap -PE $port $target 

fi 

#8 

if [ $answer = 8 ]
then 
  sudo nmap -PO $port $target 

fi 

#9

if [ $answer = 9 ]
then 
  sudo nmap -PP $port $target 

fi 

#10

if [ $answer = 10 ]
then 
  sudo nmap -PM $port $target 

fi 

#11

if [ $answer = 11 ]
then 
  sudo nmap -sY $port $target 

fi 

#12

if [ $answer = 12 ]
then 
  sudo nmap --script http-headers $port $target 

fi 


#13

if [ $answer = 13 ]
then 
  sudo nmap -A  $port $target 

fi 

#14 

if [ $answer = 14 ]
then 
  sudo nmap -sX  $port $target 

fi 

#15

if [ $answer = 15 ]
then 
  sudo nmap -sO  $port $target 

fi 

#16 

if [ $answer = 16 ]
then 
  sudo nmap -O  $port $target 

fi 

#17

if [ $answer = 17 ]
then 
  sudo nmap -sF  $port $target 

fi 
read -p "Do U Want to go back on Option [y/n]" t
done 

read -p "$red$bold||>>>>>>>>>>>>>>||Do you want to see our instagram pages||<<<<<<<<<<<<<|| (y/n) $normal"  yn  

case $yn in 
        y ) open page.html;;
        n ) echo "$red$boldThanks to u for using this tool!!!!$normal" | boxes -d ian_jones; 
                   exit;;          
        * ) echo "$red$boldThanks to u for using this tool!!!!$normal" | boxes -d ian_jones;
                   exit 1 ;; 
esac

echo "$red$bold Thanks to u for using this tool!!!!$normal" | boxes -d ian_jones

exit


